SELECT * 
FROM (
    SELECT S.SRVCLIENT AS department, COUNT(*) AS import_count
    FROM DB2INST1.SUBJECT as S
    JOIN DB2INST1.COURSEOFFERING as C on C.SBJNO = S.SBJNO
    JOIN DB2INST1.LECTURER as L on L.LECNO = C.LECNO
    WHERE S.SRVCLIENT != L.LECDEPT
    GROUP BY S.SRVCLIENT
    ORDER BY S.SRVCLIENT
) as SUB;
