SELECT * 
FROM (
    SELECT L.LECDEPT AS department, COUNT(*) AS export_count
    FROM DB2INST1.LECTURER as L
    JOIN DB2INST1.COURSEOFFERING as C on L.LECNO = C.LECNO 
    JOIN DB2INST1.SUBJECT as S on C.SBJNO = S.SBJNO
    WHERE L.LECDEPT != S.SRVCLIENT
    GROUP BY L.LECDEPT
    ORDER BY L.LECDEPT
) as SUB;
